# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  schedule:
    - cron: "0 * * * *"
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install Requirements
      run: pip install -r requirements.txt

    - name: Execute Python script
      run: |
        python scrape.py
        
    - name: setup git config
      run: |
        git config user.name ${{ secrets.USERNAME }}
        git config user.email ${{ secrets.EMAIL }}
        
    - name: commit changes
      run: |
        chmod +x ./commit.sh
        ./commit.sh

    
